from unicodedata import name
from website import db
from website import create_app
from website.models.models import User, Note, Event, Game, Character

def populatedb():
    app = create_app()
    with app.app_context():
        if Game.query.first() == None:
            GGST = Game(name='Guilty Gear Strive')
            db.session.add(GGST)
            BBCF = Game(name='Blazblue Centralfiction')
            db.session.add(BBCF)
            SFV = Game(name='Street Fighter V CE')
            db.session.add(SFV)
            db.session.commit()
        if Character.query.filter_by(game=1).first() == None:
            db.session.add(Character(name='Sol Badguy', game=1))
            db.session.add(Character(name='Ky Kiske', game=1))
            db.session.add(Character(name='May', game=1))
            db.session.add(Character(name='Faust', game=1))
            db.session.add(Character(name='Potemkin', game=1))
            db.session.add(Character(name='Chipp Zanuff', game=1))
            db.session.add(Character(name='Zato-1', game=1))
            db.session.add(Character(name='Millia Rage', game=1))
            db.session.add(Character(name='Axl Low', game=1))
            db.session.add(Character(name='Anji Mito', game=1))
            db.session.add(Character(name='I-No', game=1))
            db.session.add(Character(name='Leo Whitefang', game=1))
            db.session.add(Character(name='Ramlethal Valentine', game=1))
            db.session.add(Character(name='Giovanna', game=1))
            db.session.add(Character(name='Goldlewis Dickinson', game=1))
            db.session.add(Character(name='Jack-O Valentine', game=1))
            db.session.add(Character(name='Happy Chaos', game=1))
            db.session.add(Character(name='Baiken', game=1))
            db.session.add(Character(name='Testament', game=1))
            db.session.commit()
        if Character.query.filter_by(game=2).first() == None:
            db.session.add(Character(name='Ragna the Bloodedge', game=2))
            db.session.add(Character(name='Jin Kisaragi', game=2))
            db.session.add(Character(name='Noel Vermilion', game=2))
            db.session.add(Character(name='Rachel Alucard', game=2))
            db.session.add(Character(name='Taokaka', game=2))
            db.session.add(Character(name='Iron Tager', game=2))
            db.session.add(Character(name='Litchi Faye Ling', game=2))
            db.session.add(Character(name='Arakune', game=2))
            db.session.add(Character(name='Bang Shishigami', game=2))
            db.session.add(Character(name='Carl Clover', game=2))
            db.session.add(Character(name='Hakumen', game=2))
            db.session.add(Character(name='Nu-13', game=2))
            db.session.add(Character(name='Tsubaki Yayoi', game=2))
            db.session.add(Character(name='Hazama', game=2))
            db.session.add(Character(name='Mu-12', game=2))
            db.session.add(Character(name='Makoto Nanaya', game=2))
            db.session.add(Character(name='Valkenhayn R. Hellsing', game=2))
            db.session.add(Character(name='Platinum the Trinity', game=2))
            db.session.add(Character(name='Relius Clover', game=2))
            db.session.add(Character(name='Izayoi', game=2))
            db.session.add(Character(name='Amane Nishiki', game=2))
            db.session.add(Character(name='Bullet', game=2))
            db.session.add(Character(name='Azrael', game=2))
            db.session.add(Character(name='Kagura Mutsuki', game=2))
            db.session.add(Character(name='Kokonoe', game=2))
            db.session.add(Character(name='Yuuki Terumi', game=2))
            db.session.add(Character(name='Celica A. Mercury', game=2))
            db.session.add(Character(name='Lambda-11', game=2))
            db.session.add(Character(name='Hibiki Kohaku', game=2))
            db.session.add(Character(name='Nine the Phantom', game=2))
            db.session.add(Character(name='Naoto Kurogane', game=2))
            db.session.add(Character(name='Izanami', game=2))
            db.session.add(Character(name='Susano-oo', game=2))
            db.session.add(Character(name='Es', game=2))
            db.session.add(Character(name='Mai Natsume', game=2))
            db.session.add(Character(name='Juubei', game=2))
            db.session.commit()

if __name__ == "__main__":
    populatedb()